### ISSUE TITLE
renv in REMIND is not propperly initialised, crashing REMIND runs

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/piamenv#10]
To reproduce:
- check out REMIND from Github
  `git checkout git@gihub.com:remindmodel/remind.git ./`
- Update the renv:
  `$ make update-renv`

`updateRenv()` will do its thing, installing packages, but ultimately fail with
```
…
* Checking for updated packages ... Done!
* All packages appear to be up-to-date.
Execution halted
make: *** [Makefile:20: update-renv] Error 1
```
when it should write the `renv.lock` file.

This is reliably reproduced by both `make update-renv` and `Rscript -e "piamenv::updateRenv()"`.

Can be fixed by calling `make update-renv-all`, but that shouldn't be on the user.

**Comment by pfuehrlich-pik** [comment]
We had a `tidyverse` version in our libpath that required a newer version of `dplyr` than what we had installed. I reinstalled `tidyverse` which also updated its dependencies as required.
To fix a renv in this broken state you can `renv::install('tidyverse')`. Newly cloned and bootstrapped remind folders will get a consistent renv again.
