### ISSUE TITLE
fixDeps always installs newest, not required version of package

### ISSUE THREAD

**Issue by orichters** [pik-piam/piamenv#9]
[piamenv:fixDeps](https://github.com/pik-piam/piamenv/blob/main/R/fixDeps.R) always installs newest, not required version of package. This seems to be a bug.

If I read the source code correctly, it expects from `piamenv::checkDeps` to get passed a string such as `remind2 == 1.104.1 is required, but 1.104.0 is installed - please install: remind2@1.104.1`, but it gets `remind2 >= 1.104.1 is required, but 1.104.0 is installed - please update: remind2`. Therefore, [this grep](https://github.com/pik-piam/piamenv/blob/main/R/fixDeps.R#L31) is not working: it returns `remind2`, not `remind2@1.104.1` and therefore installs the newest, not the required version.

**Comment by mikapfl** [comment]
But the DESCRIPTION states `>=`, so the latest package is a required package. If you want a specific package version, you have to put `==` into the DESCRIPTION. Which, unfortunately, is not generally supported in R package versioning.

**Comment by mikapfl** [comment]
Asking for `>=` means you are fine with later versions and shouldn't be surprised if you get them.

**Comment by pfuehrlich-pik** [comment]
This is a very specific, nonstandard way of interpreting `>=` for a single package though, I'd strongly argue against adapting this general tool to that. If you want that specific version you could always install it manually, and fixDeps will be fine with it.

**Comment by mikapfl** [comment]
> except for moving everything into one package duckandcover

That's what facebook and microsoft are doing for their flagship products (the website and windows, respectively). The problem in the context of merging remind2 and remindmodel/remind is that people resisted making remindmodel/remind an R package in the first place, so we can't merge two packages :stuck_out_tongue:
